# Generated by Django 4.2.4 on 2023-09-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Delivery',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=23)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField(max_length=6)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
