# Generated by Django 4.2.4 on 2023-09-25 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_store', '0003_alter_items_delivery_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDelivery',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=23)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='Contact number should not be greater than 10 digits.'), django.core.validators.MinLengthValidator(limit_value=10, message='Contact number should not be less than 10 digits.')])),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.MaxLengthValidator(limit_value=6, message='Zip code should not be greater than 6 digits.'), django.core.validators.MinLengthValidator(limit_value=6, message='Zip code should not be less than 6 digits.')])),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Items_Delivery',
        ),
    ]
